config/routes.rb
Rails.application.routes.draw do
  root 'instructors#index'
  resources :instructors, :instruments, :students

end

app/models/instructor.rb
class Instructor < ActiveRecord::Base
  has_many :proficiencies
  has_many :instruments, :through => :proficiencies
end

app/models/instrument.rb
class Instrument < ActiveRecord::Base
  has_many :proficiencies
  has_many :instructors, :through => :proficiencies
end

app/models/proficiency.rb
class Proficiency < ActiveRecord::Base
  belongs_to :instructor
  belongs_to :instrument
end

app/models/student.rb
class Student < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/instructors_controller.rb
class InstructorsController < ApplicationController

  http_basic_authenticate_with name: "username", password: "password", except: [:index, :show]

  before_action :set_instructor, only: [:show, :edit, :update, :destroy]


  def index
    @instructors = Instructor.all.sort_by{|i| i.name}
    @instructor = Instructor.new
  end

  def show
  end

  def new
    @instructor = Instructor.new
  end

  def edit
  end

  def create
   @instructor = Instructor.new(instructor_params)

      if @instructor.save
        redirect_to @instructor, notice: 'Instructor was successfully created.'
      else
        render :new
      end
  end


  def update

      if @instructor.update(instructor_params)
        redirect_to @instructor, notice: 'Instructor was successfully updated. Great Job!'
      else
          render :edit
      end
  end


  def destroy
    @instructor.destroy
      redirect_to instructors_url, notice: 'Instructor was successfully destroyed.'
  end

  private

  def set_instructor
    @instructor = Instructor.find(params[:id])
  end

  def instructor_params
    params.require(:instructor).permit(:name)
  end
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  before_action :set_instrument, only: [:show, :edit, :update, :destroy]


  def index
    @instruments = Instrument.order(:name)
  end

  def show
  end

  def new
    @instrument = Instrument.new
  end

  def edit
  end

  def create
   @instrument = Instrument.new(instrument_params)

      if @instrument.save
        redirect_to @instrument, notice: 'Your Instrument was successfully created.'
      else
        render :new
      end
  end


  def update

      if @instrument.update(instrument_params)
        redirect_to @instrument, notice: 'Instrument was successfully updated. Great Job!'
      else
          render :edit
      end
  end


  def destroy
    @instrument.destroy
      redirect_to instruments_url, notice: 'Your instrument was successfully destroyed.'
  end

  private

  def set_instrument
    @instrument = Instrument.find(params[:id])
  end

  def instrument_params
    params.require(:instrument).permit(:name, :kind)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController

  before_action :set_student, only: [:show, :edit, :update, :destroy]

  def index
    @students = Student.all
  end

  def show
  end

  def new
    @student = Student.new
  end

  def edit
  end

  def create
    @student = Student.new(student_params)

    if @student.save
     redirect_to @student, notice: 'Student was successfully created. Good Job!'
   else
     render :new
    end
  end

  def update

      if @student.update(student_params)
        redirect_to @student, notice: 'Student was successfully updated. Great Job!'
      else
          render :edit
      end
  end



  def destroy
    @student.destroy

    redirect_to students_url, notice: 'Student was successfully destroyed.'
  end


private

  def set_student
  @student = Student.find(params[:id])
  end

  def student_params
  params.require(:student).permit(:name, :age)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/instructor_helper.rb
module InstructorHelper
end

app/helpers/instrument_helper.rb
module InstrumentHelper
end

app/helpers/student_helper.rb
module StudentHelper
end

app/views/instructors/_form.html.erb
<%= form_for(@instructor, remote: true) do |f| %>

  <% if @instructor.errors.any? %>

    <div id="error_explanation">
      <h2><%= pluralize(@instructor.errors.count, "error") %> prohibited this instructor from being saved:</h2>

      <ul>
      <% @instructor.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name%><br>
    <%= f.text_field :name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/instructors/_instructor.html.erb
<p>
  <strong>Name:</strong>
  <%= instructor.name %>
</p>

app/views/instructors/edit.html.erb
<h1>Edit Instructor</h1>

<%= render 'form' %>

<%= link_to 'Show', @instructor %> |
<%= link_to 'Back', instructors_path %>

app/views/instructors/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Hello, Instructors! Please create your profile</h1>
<%= render 'form' %>

<h1>Instructor</h1>

<!-- <table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead> -->

 <!--  <tbody> -->
    <% @instructors.each do |instructor| %>
    <%= render instructor %>
      <!-- <tr>
        <td><%= instructor.name %></td>
        <td><%= link_to 'Show', instructor %></td>
        <td><%= link_to 'Edit', edit_instructor_path(instructor) %></td>
        <td><%= link_to 'Destroy', instructor, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr> -->
    <% end %>
  <!-- </tbody>
</table>
 -->
<br>

<%#= link_to 'New Instructor', new_instructor_path %>

app/views/instructors/new.html.erb
<h1>Instructor</h1>

<%= render 'form' %>

<%= link_to 'Back', instructors_path %>

app/views/instructors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @instructor.name %>
</p>

<%= link_to 'Edit', edit_instructor_path(@instructor) %> |
<%= link_to 'Back', instructors_path %>

app/views/instruments/_form.html.erb
<%= form_for(@instrument) do |f| %>

  <% if @instrument.errors.any? %>

    <div id="error_explanation">
      <h2><%= pluralize(@instrument.errors.count, "error") %> prohibited this instrument from being saved:</h2>

      <ul>
      <% @instrument.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <br>
     <%= f.text_field :name %>
     <br>
     <%= f.label :kind %>
     <br>
    <%= f.text_field :kind %>
    <br>

  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/instruments/edit.html.erb
<h1>Edit Instrument</h1>

<%= render 'form' %>

<%= link_to 'Show', @instrument %> |
<%= link_to 'Back', instruments_path %>

app/views/instruments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Which musical instrument would you like to learn?</h1>

<table>
  <thead>
    <tr>
      <th>Type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @instruments.each do |instrument| %>
      <tr>
        <td><%= instrument.name %></td>
        <td><%= link_to 'Show', instrument %></td>
        <td><%= link_to 'Edit', edit_instrument_path(instrument) %></td>
        <td><%= link_to 'Destroy', instrument, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Instrument', new_instrument_path %>

app/views/instruments/new.html.erb
<h1>Instrument</h1>

<%= render 'form' %>

<%= link_to 'Back', instruments_path %>

app/views/instruments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @instrument.name %>
</p>
<p>
  <strong>Instructors:</strong>
  <% @instrument.instructors.each do |instructor| %>
  <%= instructor.name %>
  <% end %>
</p>

<%= link_to 'Edit', edit_instrument_path(@instrument) %> |
<%= link_to 'Back', instruments_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InstrumentInventory</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/students/_form.html.erb
<%= form_for(@student) do |f| %>

  <% if @student.errors.any? %>

    <div id="error_explanation">
      <h2><%= pluralize(@student.errors.count, "error") %> prohibited this student from being saved:</h2>

      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name%>
    <br>
    <%= f.text_field :name %>
    <br>
    <%= f.label :age %>
    <br>
    <%= f.number_field :age, in: 1.0 .. 100%>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/students/edit.html.erb
<h1>Edit Student</h1>

<%= render 'form' %>

<%= link_to 'Show', @student %> |
<%= link_to 'Back', students_path %>

app/views/students/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Students</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @students.each do |student| %>
      <tr>
        <td><%= student.name %></td>
        <td><%= student.age %></td>
        <td><%= link_to 'Show', student %></td>
        <td><%= link_to 'Edit', edit_student_path(student) %></td>
        <td><%= link_to 'Destroy', student, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Student', new_student_path %>

app/views/students/new.html.erb
<h1>Student</h1>

<%= render 'form' %>

<%= link_to 'Back', students_path %>

app/views/students/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @student.name %>
  <strong>Age:</strong>
  <%= @student.age %>
</p>

<%= link_to 'Edit', edit_student_path(@student) %> |
<%= link_to 'Back', students_path %>